import { Injectable } from '@nestjs/common';
import { MailService } from 'src/services/mail/mail.service';


@Injectable()
export class AssetReturnMailService extends MailService {
    async sendReqApproved(to: string): Promise<void> {
        await this.sendMail(
            to,
            'Asset Return Request Approved',
            `<p>Congratulations, your asset request is approved</p>`,
        );
    }

    async sendReqDeclined(to: string): Promise<void> {
        await this.sendMail(
            to,
            'Asset Return Request Declined',
            `<p>Sorry, your asset request is declined</p>`,
        );
    }

    async sendReqGenerated(by: string, to: string[]): Promise<void> {
        await this.sendAdminNotification(
            to,
            'Asset Return Request Generated',
            `<p>New return request generated by ${by}</p>`,
        );
    }
}
